Nativescript 5.4.0 is not accepting import with relative path, only accepts import with absolute path.
An error occurred while executing the command tns run ios --bundle --env.uglify --env.aot --env.report:

ERROR in node_modules / nativescript-grid-view / grid-view.d.ts (17,71): error TS2307: Can not find module 'ui / core / view'.
node_modules / nativescript-grid-view / grid-view.d.ts (18,64): error TS2307: Can not find module 'ui / list-view'.
node_modules / nativescript-grid-view / grid-view.d.ts (19,27): error TS2307: Can not find module 'data / observable'.
node_modules / nativescript-grid-view / angular / grid-view-comp.d.ts (20,14): error TS2416: Property 'nativeElement' in type 'GridViewComponent' is not assignable to the same property in base type 'TemplatedItemsComponent' .
  Property 'off' is missing in type 'GridView' but required in type 'TemplatedItemsView'.
(21,15): error TS2416: Property 'templatedItemsView' in type 'GridViewComponent' is not assignable to the same property in base type 'TemplatedItemsComponent' .
  Type 'GridView' is not assignable to type 'TemplatedItemsView'.

Fixed imports with absolute path so that the plugin is compatible with the new version of Nativescript 5 and 6.